export const ADD_PATIENT = "ADD_PATIENT";
export const ADD_THERAPIST = "ADD_THERAPIST";
export const ADD_SCHEDULER = "ADD_SCHEDULE";
export const RESET_SCHEDULER = "RESET_SCHEDULE";
export const RESET_PATIENT = "RESET_PATIENT";